import "dotenv/config";
import postgres from "postgres";

async function main() {
  const sql = postgres(process.env.DATABASE_URL!);
  try {
    console.log("=== MIGRATION: finance-caisse (mouvements_caisse, pertes_financieres, remboursements_fournisseurs, factures_fournisseur) ===\n");

    await sql`ALTER TABLE mouvements_caisse ADD COLUMN IF NOT EXISTS entite_type VARCHAR(50)`;
    console.log("  ✓ mouvements_caisse.entite_type");

    await sql`ALTER TABLE mouvements_caisse ADD COLUMN IF NOT EXISTS entite_id INTEGER`;
    console.log("  ✓ mouvements_caisse.entite_id");

    await sql`ALTER TABLE mouvements_caisse ADD COLUMN IF NOT EXISTS categorie_depense VARCHAR(100)`;
    console.log("  ✓ mouvements_caisse.categorie_depense");

    await sql`CREATE TABLE IF NOT EXISTS pertes_financieres (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      agence_id INTEGER NOT NULL REFERENCES agences(id),
      produit_id INTEGER REFERENCES produits(id),
      quantite NUMERIC(12,2) NOT NULL,
      cout_unitaire NUMERIC(12,2) NOT NULL,
      montant_perte NUMERIC(12,2) NOT NULL,
      type_perte VARCHAR(50) NOT NULL,
      motif TEXT,
      reference VARCHAR(100),
      reference_type VARCHAR(50),
      effectue_par INTEGER REFERENCES utilisateurs(id),
      date_perte TIMESTAMP DEFAULT now()
    )`;
    console.log("  ✓ table pertes_financieres");

    await sql`ALTER TABLE remboursements_fournisseurs ADD COLUMN IF NOT EXISTS caisse_id INTEGER REFERENCES caisses(id)`;
    console.log("  ✓ remboursements_fournisseurs.caisse_id");

    await sql`ALTER TABLE factures_fournisseur ADD COLUMN IF NOT EXISTS montant_paye NUMERIC(12,2) DEFAULT '0'`;
    console.log("  ✓ factures_fournisseur.montant_paye");

    await sql`ALTER TABLE factures_fournisseur ADD COLUMN IF NOT EXISTS montant_restant NUMERIC(12,2) DEFAULT '0'`;
    console.log("  ✓ factures_fournisseur.montant_restant");

    console.log("\n=== MIGRATION TERMINÉE ===");
  } finally {
    await sql.end();
  }
}

main().catch((e) => {
  console.error("Migration failed:", e);
  process.exit(1);
});
