import type { ReportInput } from "./defs";

export interface ReportTemplate {
  id: string;
  nom: string;
  description: string;
  groupe: "ventes" | "marges" | "performances" | "scolaire";
  params: ReportInput;
}

export const REPORT_TEMPLATES: ReportTemplate[] = [
  {
    id: "benefice-produits",
    nom: "Bénéfice d'un ou plusieurs produits",
    description: "CA, coût et marge brute d'une sélection de produits sur une période.",
    groupe: "marges",
    params: {
      dimension: "produit",
      measures: ["ca", "quantite", "cout", "margeBrute"],
      ratios: ["tauxMarge"],
      filters: {},
      comparePrevious: true,
      sortBy: "measure:margeBrute",
      sortDir: "desc",
      limit: 100,
      offset: 0,
    },
  },
  {
    id: "ca-marge-jour",
    nom: "CA et marge au jour le jour",
    description: "Évolution quotidienne du chiffre d'affaires, du coût et de la marge.",
    groupe: "ventes",
    params: {
      dimension: "periode",
      periodeUnite: "jour",
      measures: ["ca", "margeBrute"],
      ratios: ["tauxMarge"],
      filters: {},
      comparePrevious: true,
      sortBy: "dimension",
      sortDir: "asc",
      limit: 365,
      offset: 0,
    },
  },
  {
    id: "ventes-par-categorie",
    nom: "Ventes par catégorie",
    description: "Ventilation des ventes et de la marge par catégorie de produits.",
    groupe: "ventes",
    params: {
      dimension: "categorie",
      measures: ["ca", "quantite", "margeBrute"],
      ratios: ["tauxMarge"],
      filters: {},
      comparePrevious: true,
      sortBy: "measure:ca",
      sortDir: "desc",
      limit: 100,
      offset: 0,
    },
  },
  {
    id: "ventes-par-vendeur",
    nom: "Ventes par vendeur",
    description: "Performance de chaque vendeur : CA, tickets, panier moyen.",
    groupe: "performances",
    params: {
      dimension: "vendeur",
      measures: ["ca", "nbTickets", "nbClientsDistincts"],
      ratios: ["panierMoyen"],
      filters: {},
      comparePrevious: false,
      sortBy: "measure:ca",
      sortDir: "desc",
      limit: 100,
      offset: 0,
    },
  },
  {
    id: "ventes-par-caisse",
    nom: "Ventes par caisse et mode de paiement",
    description: "Ventilation par caisse puis par mode de paiement.",
    groupe: "ventes",
    params: {
      dimension: "caisse",
      measures: ["ca", "nbTickets"],
      ratios: ["panierMoyen"],
      filters: {},
      comparePrevious: false,
      sortBy: "measure:ca",
      sortDir: "desc",
      limit: 100,
      offset: 0,
    },
  },
  {
    id: "ventes-par-agence",
    nom: "Ventes par agence",
    description: "Comparatif des agences du réseau (admin réseau uniquement).",
    groupe: "ventes",
    params: {
      dimension: "agence",
      measures: ["ca", "margeBrute", "nbTickets"],
      ratios: ["tauxMarge", "panierMoyen"],
      filters: {},
      comparePrevious: true,
      sortBy: "measure:ca",
      sortDir: "desc",
      limit: 100,
      offset: 0,
    },
  },
  {
    id: "top-produits-marge",
    nom: "Top produits par marge",
    description: "Les produits qui génèrent le plus de marge brute sur la période.",
    groupe: "marges",
    params: {
      dimension: "produit",
      measures: ["ca", "quantite", "margeBrute"],
      ratios: ["tauxMarge"],
      filters: {},
      comparePrevious: false,
      sortBy: "measure:margeBrute",
      sortDir: "desc",
      limit: 50,
      offset: 0,
    },
  },
  {
    id: "ventes-sous-cout",
    nom: "Produits vendus sous le coût",
    description: "Détection des pertes : produits vendus à perte sur la période.",
    groupe: "marges",
    params: {
      dimension: "produit",
      measures: ["ca", "quantite", "pertes", "margeBrute"],
      ratios: ["tauxMarge"],
      filters: {},
      comparePrevious: false,
      sortBy: "measure:pertes",
      sortDir: "desc",
      limit: 50,
      offset: 0,
    },
  },
  {
    id: "remises-par-categorie",
    nom: "Remises accordées par catégorie",
    description: "Montant et taux de remise par catégorie de produits.",
    groupe: "marges",
    params: {
      dimension: "categorie",
      measures: ["ca", "remises", "margeBrute"],
      ratios: ["tauxRemise", "tauxMarge"],
      filters: {},
      comparePrevious: false,
      sortBy: "measure:remises",
      sortDir: "desc",
      limit: 100,
      offset: 0,
    },
  },
  {
    id: "ventes-scolaires",
    nom: "Ventes par niveau / classe / filière",
    description: "Ventilation du matériel scolaire par niveau, classe, filière et sous-système.",
    groupe: "scolaire",
    params: {
      dimension: "niveau",
      measures: ["ca", "quantite", "nbTickets"],
      ratios: [],
      filters: { typesProduit: ["FOURNITURE"] },
      comparePrevious: true,
      sortBy: "measure:ca",
      sortDir: "desc",
      limit: 100,
      offset: 0,
    },
  },
  {
    id: "fidelite-clients",
    nom: "Top clients",
    description: "Les meilleurs clients : CA, tickets et panier moyen.",
    groupe: "performances",
    params: {
      dimension: "client",
      measures: ["ca", "nbTickets", "nbProduitsDistincts"],
      ratios: ["panierMoyen"],
      filters: {},
      comparePrevious: false,
      sortBy: "measure:ca",
      sortDir: "desc",
      limit: 50,
      offset: 0,
    },
  },
  {
    id: "editeurs-fournisseurs",
    nom: "Ventes par éditeur et fournisseur",
    description: "Poids de chaque éditeur et fournisseur dans le chiffre d'affaires.",
    groupe: "ventes",
    params: {
      dimension: "editeur",
      measures: ["ca", "quantite", "margeBrute"],
      ratios: ["tauxMarge"],
      filters: {},
      comparePrevious: false,
      sortBy: "measure:ca",
      sortDir: "desc",
      limit: 100,
      offset: 0,
    },
  },
  {
    id: "resume-mensuel",
    nom: "Résumé mensuel",
    description: "Synthèse CA, marge, remises, pertes et panier moyen par mois.",
    groupe: "ventes",
    params: {
      dimension: "periode",
      periodeUnite: "mois",
      measures: ["ca", "margeBrute", "remises", "pertes", "nbTickets"],
      ratios: ["tauxMarge", "panierMoyen", "tauxRemise"],
      filters: {},
      comparePrevious: true,
      sortBy: "dimension",
      sortDir: "asc",
      limit: 60,
      offset: 0,
    },
  },
];
