import { boolean, date, decimal, integer, pgTable, serial, text, timestamp, varchar } from "drizzle-orm/pg-core";
import { agences } from "./agences";

export const employes = pgTable("employes", {
  id: serial("id").primaryKey(),
  matricule: varchar("matricule", { length: 30 }).notNull().unique(),
  nom: varchar("nom", { length: 255 }).notNull(),
  prenom: varchar("prenom", { length: 255 }).notNull(),
  dateNaissance: date("date_naissance"),
  sexe: varchar("sexe", { length: 1 }),
  emailPersonnel: varchar("email_personnel", { length: 255 }),
  telephone: varchar("telephone", { length: 50 }),
  telephoneSecondaire: varchar("telephone_secondaire", { length: 50 }),
  adresse: text("adresse"),
  ville: varchar("ville", { length: 100 }),
  typeEmploye: varchar("type_employe", { length: 30 }).notNull().default("permanent"),
  fonction: varchar("fonction", { length: 100 }).notNull(),
  dateEmbauche: date("date_embauche"),
  dateFinContrat: date("date_fin_contrat"),
  periodeEssaiFin: date("periode_essai_fin"),
  salaireBase: decimal("salaire_base", { precision: 12, scale: 0 }),
  devise: varchar("devise", { length: 3 }).default("XOF"),
  modePaie: varchar("mode_paie", { length: 20 }).default("mensuel"),
  numCnss: varchar("num_cnss", { length: 30 }),
  numCompteBancaire: varchar("num_compte_bancaire", { length: 50 }),
  banque: varchar("banque", { length: 100 }),
  typePieceIdentite: varchar("type_piece_identite", { length: 30 }),
  numPieceIdentite: varchar("num_piece_identite", { length: 50 }),
  pieceExpireLe: date("piece_expire_le"),
  diplome: varchar("diplome", { length: 255 }),
  statut: varchar("statut", { length: 20 }).default("actif"),
  photoUrl: text("photo_url"),
  userId: integer("user_id"),
  agenceId: integer("agence_id").notNull().references(() => agences.id),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
