import { boolean, date, decimal, integer, pgTable, serial, text, timestamp, varchar } from "drizzle-orm/pg-core";
import { agences } from "./agences";
import { hrWorkCycles } from "./rh_parametrage";

export const employes = pgTable("employes", {
  id: serial("id").primaryKey(),
  matricule: varchar("matricule", { length: 30 }).notNull().unique(),
  civilite: varchar("civilite", { length: 10 }),
  nom: varchar("nom", { length: 255 }).notNull(),
  prenom: varchar("prenom", { length: 255 }).notNull(),
  dateNaissance: date("date_naissance"),
  lieuNaissance: varchar("lieu_naissance", { length: 120 }),
  sexe: varchar("sexe", { length: 1 }),
  emailPersonnel: varchar("email_personnel", { length: 255 }),
  telephone: varchar("telephone", { length: 50 }),
  telephoneSecondaire: varchar("telephone_secondaire", { length: 50 }),
  adresse: text("adresse"),
  ville: varchar("ville", { length: 100 }),
  contactUrgenceNom: varchar("contact_urgence_nom", { length: 255 }),
  contactUrgenceTelephone: varchar("contact_urgence_telephone", { length: 50 }),
  typeEmploye: varchar("type_employe", { length: 30 }).notNull().default("permanent"),
  fonction: varchar("fonction", { length: 100 }).notNull(),
  departmentId: integer("department_id"),
  positionId: integer("position_id"),
  workCycleId: integer("work_cycle_id").references(() => hrWorkCycles.id),
  managerId: integer("manager_id"),
  dateEmbauche: date("date_embauche"),
  dateFinContrat: date("date_fin_contrat"),
  periodeEssaiFin: date("periode_essai_fin"),
  salaireBase: decimal("salaire_base", { precision: 12, scale: 0 }),
  devise: varchar("devise", { length: 3 }).default("XOF"),
  modePaie: varchar("mode_paie", { length: 30 }).default("SALAIRE_MENSUEL"),
  forfaitHebdomadaire: decimal("forfait_hebdomadaire", { precision: 12, scale: 0 }),
  numCnss: varchar("num_cnss", { length: 30 }),
  niu: varchar("niu", { length: 30 }),
  numCompteBancaire: varchar("num_compte_bancaire", { length: 50 }),
  banque: varchar("banque", { length: 100 }),
  typePieceIdentite: varchar("type_piece_identite", { length: 30 }),
  numPieceIdentite: varchar("num_piece_identite", { length: 50 }),
  pieceExpireLe: date("piece_expire_le"),
  diplome: varchar("diplome", { length: 255 }),
  langues: varchar("langues", { length: 255 }), // specs MVP 06_Competences (langues maîtrisées)
  logiciels: varchar("logiciels", { length: 255 }), // specs MVP 06_Competences (logiciels maîtrisés)
  pointsFort: text("points_fort"), // specs MVP 06_Competences
  axesAmelioration: text("axes_amelioration"), // specs MVP 06_Competences
  notes: text("notes"),
  statut: varchar("statut", { length: 20 }).default("actif"),
  photoUrl: text("photo_url"),
  dateSortie: date("date_sortie"),
  motifSortie: varchar("motif_sortie", { length: 40 }),
  detailMotifSortie: text("detail_motif_sortie"),
  reembauchable: boolean("reembauchable").default(true),
  sortieChangedBy: integer("sortie_changed_by"),
  sortieChangedAt: timestamp("sortie_changed_at"),
  userId: integer("user_id"),
  agenceId: integer("agence_id").notNull().references(() => agences.id),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
