import "dotenv/config";
import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: [
    "./src/schema/agences.ts",
    "./src/schema/alertes.ts",
    "./src/schema/annees_scolaires.ts",
    "./src/schema/audit_logs.ts",
    "./src/schema/bons_reception.ts",
    "./src/schema/caisses.ts",
    "./src/schema/categories.ts",
    "./src/schema/clients.ts",
    "./src/schema/codes_barres.ts",
    "./src/schema/comptabilite.ts",
    "./src/schema/deconditionnements.ts",
    "./src/schema/depenses.ts",
    "./src/schema/dettes.ts",
    "./src/schema/editeurs.ts",
    "./src/schema/emplacements.ts",
    "./src/schema/employes.ts",
    "./src/schema/entrepot.ts",
    "./src/schema/fournisseurs.ts",
    "./src/schema/inventaires.ts",
    "./src/schema/inventaires_sessions.ts",
    "./src/schema/listes_scolaires.ts",
    "./src/schema/lots.ts",
    "./src/schema/modeles_emballage.ts",
    "./src/schema/mouvements_stock.ts",
    "./src/schema/paiements.ts",
    "./src/schema/permissions.ts",
    "./src/schema/platform.ts",
    "./src/schema/produit_unites.ts",
    "./src/schema/produits.ts",
    "./src/schema/produits_fournisseurs.ts",
    "./src/schema/reconditionnements.ts",
    "./src/schema/retours.ts",
    "./src/schema/role_permissions.ts",
    "./src/schema/roles.ts",
    "./src/schema/sessions_caisse.ts",
    "./src/schema/sous_systemes.ts",
    "./src/schema/stocks.ts",
    "./src/schema/stocks_unites.ts",
    "./src/schema/tarifs.ts",
    "./src/schema/tarification.ts",
    "./src/schema/transferts_stock.ts",
    "./src/schema/unites_mesure.ts",
    "./src/schema/unites_mesure_produits.ts",
    "./src/schema/user_roles.ts",
    "./src/schema/utilisateurs.ts",
    "./src/schema/utilisations_avoir.ts",
    "./src/schema/ventes.ts",
    "./src/schema/verification_tokens.ts",
    "./src/schema/travaux_export.ts",
  ],
  out: "./drizzle",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
    ssl: { rejectUnauthorized: false },
  },
});
